#!/bin/bash
echo "*******************" >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log
echo "Postrm run ${serverversion} with $1 argument" >> /var/log/tellervo-installation.log
date '+%R.%S' >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log


   
if [ $1 = 'remove' ]; then
   rm /usr/share/tellervo-server/*.backup
   rm /usr/share/tellervo-server/server_credentials
   rm /usr/share/tellervo-server/set_database_permission.sql
   rmdir /usr/share/tellervo-server
   rm /var/www/tellervo/config.php
   rm /var/www/tellervo/systemconfig.php
   rmdir /var/www/tellervo
   
   
#elif [ $1 = 'upgrade' ]; then   
   

   
#elif [ $1 = 'deconfigure' ]; then

elif [ $1 = 'failed-upgrade' ]; then

	echo "Previous version postrm script failed, but continuing anyway..." >> /var/log/tellervo-installation.log

fi


echo "*******************" >> /var/log/tellervo-installation.log
echo "*******************\n\n\n" >> /var/log/tellervo-installation.log

exit 0; 