#!/bin/bash
echo "*******************" >> /var/log/tellervo-installation.log
echo "Postrm run ${serverversion} with $1 argument" >> /var/log/tellervo-installation.log
date '+%R.%S' >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log


   
if [ $1 = 'remove' ]; then
   rm /usr/share/tellervo-server/server_credentials
   rm /usr/share/tellervo-server/set_database_permission.sql
   rmdir /usr/share/tellervo-server
   rm /var/www/tellervo-webservice/config.php
   rm /var/www/tellervo-webservice/systemconfig.php
   rmdir /var/www/tellervo-webservice
   
   
elif [ $1 = 'upgrade' ]; then   
   
    if [ -e "/tmp/config.php" ]
    then
      echo "Reinstating config.php from previous installation" >> /var/log/tellervo-installation.log
      mv /tmp/config.php /var/www/tellervo-webservice/
      echo "Regenerating systemconfig.php" >> /var/log/tellervo-installation.log
      /usr/bin/tellervo-server --sysconfig
      echo "Testing configuration" >> /var/log/tellervo-installation.log
      /usr/bin/tellervo-server --test
	  exit
    fi
   
#elif [ $1 = 'deconfigure' ]; then

#elif [ $1 = 'failed-upgrade' ]; then


fi
exit 0; 