#!/bin/bash
echo "*******************" >> /var/log/corina-installation.log
echo "Prerm run ${serverversion} with $1 argument" >> /var/log/corina-installation.log
date '+%R.%S' >> /var/log/corina-installation.log
echo "*******************" >> /var/log/corina-installation.log

if [ $1 = 'upgrade' ]; then

   ## Upgrading so, move aside config.php file so
   ## so it doesn't get over-written
   
   echo "Upgrading Corina server to a new version" >> /var/log/corina-installation.log
   if [ -e "/var/www/corina-webservice/config.php" ];
   then
     echo "Backing up config.php for reinstatement after the upgrade" >> /var/log/corina-installation.log
     cp /var/www/corina-webservice/config.php /tmp/
   fi
   
#elif [ $1 = 'remove' ]; then

#elif [ $1 = 'deconfigure' ]; then

#elif [ $1 = 'failed-upgrade' ]; then


fi
exit 0;         