#!/bin/bash
echo "*******************" >> /var/log/tellervo-installation.log
echo "Prerm run ${serverversion} with $1 argument" >> /var/log/tellervo-installation.log
date '+%R.%S' >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log

if [ $1 = 'upgrade' ]; then

   ## Upgrading so, move aside config.php file so
   ## so it doesn't get over-written
   
   echo "Upgrading Tellervo server to a new version" >> /var/log/tellervo-installation.log

elif [ $1 = 'failed-upgrade' ]; then

   echo "Previous versions prerm script failed, but continuing anyway... " >> /var/log/tellervo-installation.log
   exit 0;   
   
   
#elif [ $1 = 'remove' ]; then
   
#elif [ $1 = 'deconfigure' ]; then



fi
exit 0;         