//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.25 at 01:30:38 AM PDT 
//


package org.tridas.schema;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.tridas.org/1.1}unit"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="diameter" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "dimensions")
public class TridasDimensions {

    @XmlElementRefs({
        @XmlElementRef(name = "depth", namespace = "http://www.tridas.org/1.1", type = JAXBElement.class),
        @XmlElementRef(name = "width", namespace = "http://www.tridas.org/1.1", type = JAXBElement.class),
        @XmlElementRef(name = "diameter", namespace = "http://www.tridas.org/1.1", type = JAXBElement.class),
        @XmlElementRef(name = "height", namespace = "http://www.tridas.org/1.1", type = JAXBElement.class),
        @XmlElementRef(name = "unit", namespace = "http://www.tridas.org/1.1", type = TridasUnit.class)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Height" is used by two different parts of a schema. See: 
     * line 408 of file:/S:/workspaces/dendro/Corina-dev/src/edu/cornell/dendro/webservice/schemas/tridas.xsd
     * line 405 of file:/S:/workspaces/dendro/Corina-dev/src/edu/cornell/dendro/webservice/schemas/tridas.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link TridasUnit }
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
