/*******************************************************************************
 * Copyright (C) 2011 Peter Brewer.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     Peter Brewer
 ******************************************************************************/
package org.tellervo.desktop.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BugReportInfoPanel.java
 *
 * Created on Feb 22, 2009, 12:19:42 PM
 */

import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lucas Madar
 */
@SuppressWarnings("serial")
public class BugSubmissionPanel extends javax.swing.JPanel {

    /** Creates new form BugReportInfoPanel */
    public BugSubmissionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane3 = new JScrollPane();
        lstAttachments = new JList();
        btnSubmit = new JButton();
        pbProgress = new JProgressBar();
        txtEmailAddress = new JTextField();
        txtProgressLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        txtComments = new JTextArea();

        jLabel1.setText("E-mail address:");

        jLabel2.setText("Further information including what you were doing...");

        jLabel3.setText("File attachments:");

        lstAttachments.setModel(new AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstAttachments);

        btnSubmit.setText("Submit bug report to developers");

        txtProgressLabel.setText("[no info]");
        setLayout(new MigLayout("", "[508px][83px,grow,fill]", "[15px][19px][15px][90px,grow][14px][15px][25px]"));

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);
        add(jScrollPane1, "cell 0 3 1 4,grow");
        add(jLabel1, "cell 0 0,growx,aligny top");
        add(jLabel2, "cell 0 2,alignx left,aligny top");
        add(txtEmailAddress, "cell 0 1,growx,aligny top");
        add(txtProgressLabel, "cell 1 5,growx,aligny top");
        add(pbProgress, "cell 1 4,growx,aligny top");
        add(jLabel3, "cell 1 0,growx,aligny top");
        add(btnSubmit, "cell 1 6,alignx right,aligny top");
        add(jScrollPane3, "cell 1 1 1 3,grow");
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    protected JButton btnSubmit;
    protected JLabel jLabel1;
    protected JLabel jLabel2;
    protected JLabel jLabel3;
    protected JScrollPane jScrollPane1;
    protected JScrollPane jScrollPane3;
    protected JList lstAttachments;
    protected JProgressBar pbProgress;
    protected JTextArea txtComments;
    protected JTextField txtEmailAddress;
    protected JLabel txtProgressLabel;
    // End of variables declaration                   

}
