CREATE ROLE "Webgroup"
  NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;
  
CREATE ROLE apacheuser LOGIN
  ENCRYPTED PASSWORD 'md57292105d0cca2a6f4eeea7ed8b931f40'
  NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE;
GRANT "Webgroup" TO apacheuser;