package edu.cornell.dendro.corina.tridasv2.ui;
/*
 * LocationGeometry.java
 *
 * Created on August 3, 2009, 11:01 AM
 */



/**
 *
 * @author  peterbrewer
 */
public class LocationGeometryUI extends javax.swing.JPanel {
    
    /** Creates new form LocationGeometry */
    public LocationGeometryUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDMS = new javax.swing.JPanel();
        lblLong = new javax.swing.JLabel();
        lblLat = new javax.swing.JLabel();
        spnDMSLatDeg = new javax.swing.JSpinner();
        lblLatDeg = new javax.swing.JLabel();
        spnDMSLatMin = new javax.swing.JSpinner();
        lblLatMin = new javax.swing.JLabel();
        spnDMSLatSec = new javax.swing.JSpinner();
        lblLatSec = new javax.swing.JLabel();
        spnDMSLongDeg = new javax.swing.JSpinner();
        lblLongDeg = new javax.swing.JLabel();
        spnDMSLongMin = new javax.swing.JSpinner();
        lblLongMin = new javax.swing.JLabel();
        spnDMSLongSec = new javax.swing.JSpinner();
        lblLongSec = new javax.swing.JLabel();
        cboLatLongStyle = new javax.swing.JComboBox();
        lblFormat = new javax.swing.JLabel();
        txtGPSFilename = new javax.swing.JTextField();
        lblGPSFilename = new javax.swing.JLabel();
        btnGPSBrowse = new javax.swing.JButton();
        cboDatum = new javax.swing.JComboBox();
        lblDatum = new javax.swing.JLabel();
        cboWaypoint = new javax.swing.JComboBox();
        lblWaypoint = new javax.swing.JLabel();
        radGPS = new javax.swing.JRadioButton();
        radManual = new javax.swing.JRadioButton();
        panelButton = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnViewMap = new javax.swing.JButton();
        lblRadio = new javax.swing.JLabel();
        panelDecDeg = new javax.swing.JPanel();
        lblDDLong = new javax.swing.JLabel();
        lblDDLat = new javax.swing.JLabel();
        spnDDLat = new javax.swing.JSpinner();
        spnDDLong = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 350));
        setPreferredSize(null);

        lblLong.setText("Longitude:");

        lblLat.setText("Latitude:");

        spnDMSLatDeg.setModel(new javax.swing.SpinnerNumberModel(0, -90, 90, 1));

        lblLatDeg.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLatDeg.setText("¡");

        spnDMSLatMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        lblLatMin.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLatMin.setText("'");

        spnDMSLatSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        lblLatSec.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLatSec.setText("''");

        spnDMSLongDeg.setModel(new javax.swing.SpinnerNumberModel(0, -180, 180, 1));

        lblLongDeg.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLongDeg.setText("¡");

        spnDMSLongMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        lblLongMin.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLongMin.setText("'");

        spnDMSLongSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        lblLongSec.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        lblLongSec.setText("''");

        org.jdesktop.layout.GroupLayout panelDMSLayout = new org.jdesktop.layout.GroupLayout(panelDMS);
        panelDMS.setLayout(panelDMSLayout);
        panelDMSLayout.setHorizontalGroup(
            panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDMSLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblLat)
                    .add(lblLong))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, Short.MAX_VALUE)
                .add(panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(spnDMSLongDeg)
                    .add(spnDMSLatDeg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelDMSLayout.createSequentialGroup()
                        .add(lblLatDeg)
                        .add(10, 10, 10)
                        .add(spnDMSLatMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblLatMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(spnDMSLatSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblLatSec))
                    .add(panelDMSLayout.createSequentialGroup()
                        .add(lblLongDeg)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(spnDMSLongMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblLongMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(spnDMSLongSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblLongSec)))
                .addContainerGap())
        );
        panelDMSLayout.setVerticalGroup(
            panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDMSLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblLat)
                    .add(lblLatDeg)
                    .add(spnDMSLatMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblLatMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDMSLatSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblLatSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDMSLatDeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDMSLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblLong)
                    .add(lblLongDeg)
                    .add(spnDMSLongMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblLongMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDMSLongSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblLongSec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDMSLongDeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboLatLongStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Decimal degrees", "Degrees, minutes and seconds" }));

        lblFormat.setText("Format:");

        lblGPSFilename.setText("GPS filename:");

        btnGPSBrowse.setText("Browse");

        cboDatum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WGS84" }));

        lblDatum.setText("Datum:");

        lblWaypoint.setText("Waypoint:");

        radGPS.setText("using waypoint from GPS");


        radManual.setText("manually");

        btnOK.setText("OK");

        btnCancel.setText("Cancel");

        btnViewMap.setText("View on map");

        org.jdesktop.layout.GroupLayout panelButtonLayout = new org.jdesktop.layout.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnViewMap)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 359, Short.MAX_VALUE)
                .add(btnCancel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnOK)
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .add(panelButtonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnOK)
                    .add(btnCancel)
                    .add(btnViewMap))
                .addContainerGap())
        );

        lblRadio.setText("Set location:");

        lblDDLong.setText("Longitude:");

        lblDDLat.setText("Latitude:");
        lblDDLat.setPreferredSize(new java.awt.Dimension(85, 16));

        spnDDLat.setModel(new javax.swing.SpinnerNumberModel(0.0d, -90.0d, 90.0d, 0.10000000149011612d));

        spnDDLong.setModel(new javax.swing.SpinnerNumberModel(0.0d, -90.0d, 90.0d, 0.10000000149011612d));

        org.jdesktop.layout.GroupLayout panelDecDegLayout = new org.jdesktop.layout.GroupLayout(panelDecDeg);
        panelDecDeg.setLayout(panelDecDegLayout);
        panelDecDegLayout.setHorizontalGroup(
            panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDecDegLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblDDLat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDDLong))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(spnDDLat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDDLong, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDecDegLayout.setVerticalGroup(
            panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelDecDegLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDDLat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(spnDDLat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDecDegLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(spnDDLong, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDDLong))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(148, 148, 148)
                .add(radManual)
                .add(18, 18, 18)
                .add(radGPS, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .add(101, 101, 101))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblRadio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 617, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblGPSFilename, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblWaypoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDatum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblFormat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cboLatLongStyle, 0, 408, Short.MAX_VALUE)
                    .add(cboDatum, 0, 408, Short.MAX_VALUE)
                    .add(cboWaypoint, 0, 408, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtGPSFilename, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnGPSBrowse)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(panelDMS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(panelDecDeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(panelButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRadio)
                    .add(radManual)
                    .add(radGPS))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblGPSFilename)
                    .add(btnGPSBrowse)
                    .add(txtGPSFilename, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblWaypoint)
                    .add(cboWaypoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDatum)
                    .add(cboDatum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblFormat)
                    .add(cboLatLongStyle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDMS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelDecDeg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnGPSBrowse;
    protected javax.swing.JButton btnOK;
    protected javax.swing.JButton btnViewMap;
    protected javax.swing.JComboBox cboDatum;
    protected javax.swing.JComboBox cboLatLongStyle;
    protected javax.swing.JComboBox cboWaypoint;
    protected javax.swing.JLabel lblDDLat;
    protected javax.swing.JLabel lblDDLong;
    protected javax.swing.JLabel lblDatum;
    protected javax.swing.JLabel lblFormat;
    protected javax.swing.JLabel lblGPSFilename;
    protected javax.swing.JLabel lblLat;
    protected javax.swing.JLabel lblLatDeg;
    protected javax.swing.JLabel lblLatMin;
    protected javax.swing.JLabel lblLatSec;
    protected javax.swing.JLabel lblLong;
    protected javax.swing.JLabel lblLongDeg;
    protected javax.swing.JLabel lblLongMin;
    protected javax.swing.JLabel lblLongSec;
    protected javax.swing.JLabel lblRadio;
    protected javax.swing.JLabel lblWaypoint;
    protected javax.swing.JPanel panelButton;
    protected javax.swing.JPanel panelDMS;
    protected javax.swing.JPanel panelDecDeg;
    protected javax.swing.JRadioButton radGPS;
    protected javax.swing.JRadioButton radManual;
    protected javax.swing.JSpinner spnDDLat;
    protected javax.swing.JSpinner spnDDLong;
    protected javax.swing.JSpinner spnDMSLatDeg;
    protected javax.swing.JSpinner spnDMSLatMin;
    protected javax.swing.JSpinner spnDMSLatSec;
    protected javax.swing.JSpinner spnDMSLongDeg;
    protected javax.swing.JSpinner spnDMSLongMin;
    protected javax.swing.JSpinner spnDMSLongSec;
    protected javax.swing.JTextField txtGPSFilename;
    // End of variables declaration//GEN-END:variables
    
}
