/*
 * Site.java
 *
 * Created on June 2, 2008, 3:38 PM
 */

package edu.cornell.dendro.corina.gui.newui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import edu.cornell.dendro.corina.core.App;
import edu.cornell.dendro.corina.site.Site;
import edu.cornell.dendro.corina.site.Subsite;
import edu.cornell.dendro.corina.ui.Alert;
import edu.cornell.dendro.corina.util.Center;
import edu.cornell.dendro.corina.webdbi.IntermediateResource;
import edu.cornell.dendro.corina.webdbi.MeasurementResource;
import edu.cornell.dendro.corina.webdbi.PrototypeLoadDialog;

/**
 *
 * @author  peterbrewer
 */
public class SiteDialog extends BaseNewDialog<Site> {
    
    /** Creates new form Site */
    public SiteDialog() {
        //super(parent, modal);
        initComponents();
        
        initialize();
        //Center.center(this);
    }
    
	private void initialize() {
    	
    	// forced formatting on the site code box
		setCapsNoWhitespace(txtSiteCode);
    	
    	// When the code is changed, listen and ensure length
    	// We use this as one condition to allow the Apply button to be enabled
    	setFieldValidateButtons(txtSiteCode);

    	// When the name is changed, listen and ensure length and not defaults!
    	// We use this as the second condition to allow the Apply button to be enabled
    	setFieldValidateButtons(txtSiteName);
    	
    	// on focus, select all (for nice tabbing)
    	setSelectAllOnFocus(txtSiteName);
    	
    	// on focus, select all (for nice tabbing) #2
    	setSelectAllOnFocus(txtSiteCode);

    	// apply button
    	btnApply.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent ae) {
    			commit();
    		}
    	});
    	//getRootPane().setDefaultButton(btnApply);
    	btnApply.setEnabled(false);
    	
    	// cancel button
    	btnCancel.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent ae) {
    			dispose();
    		}
    	});
    	
    	// set our default validation state
    	validateForm();
    }

    public void commit() {
    	Site site = new Site(Site.ID_NEW, txtSiteName.getText(), txtSiteCode.getText());
    	IntermediateResource ir = new IntermediateResource((Site) null, site);
    	
    	if(!createObject(ir))
    		return;

		if(ir.getObject().get(0) instanceof Site) {
			setNewObject((Site) ir.getObject().get(0));
	    	// add the site to the site list
			App.sites.addSite(getNewObject());
		}

		dispose();
    }
    
    protected void validateForm() {
    	boolean codeOk, nameOk;
		int len;
		
		// first, site code
		len = txtSiteCode.getText().length();
		if(len > 1)
			codeOk = true;
		else
			codeOk = false;
		
		// then, site name
		len = txtSiteName.getText().length();

		if(len > 2 && !txtSiteName.getText().equals("Name of this site"))
			nameOk = true;
		else
			nameOk = false;
		
		if(!nameOk)
			txtSiteName.setBackground(Color.CYAN);
		else 
			txtSiteName.setBackground(Color.WHITE);

		if(!codeOk)
			txtSiteCode.setBackground(Color.CYAN);
		else 
			txtSiteCode.setBackground(Color.WHITE);

		setFormValidated(codeOk && nameOk);
		//btnApply.setEnabled(codeOk && nameOk);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSiteCode = new javax.swing.JTextField();
        txtSiteName = new javax.swing.JTextField();
        lblSiteCode = new javax.swing.JLabel();
        lblSiteName = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        seperatorButtons = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Site");

        txtSiteName.setText("");
        txtSiteCode.setToolTipText("Code name for this site");

        txtSiteName.setText("Name of this site");
        txtSiteName.setToolTipText("Name of this site");

        lblSiteCode.setText("Site code:");

        lblSiteName.setText("Site name:");

        btnCancel.setText("Cancel");

        btnApply.setText("Apply");

        seperatorButtons.setBackground(new java.awt.Color(153, 153, 153));
        seperatorButtons.setOpaque(true);

        /*
        org.jdesktop.layout.GroupLayout panelButtonsLayout = new org.jdesktop.layout.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .add(btnApply)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCancel)
                .add(5, 5, 5))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, seperatorButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelButtonsLayout.createSequentialGroup()
                .add(seperatorButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelButtonsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnCancel)
                    .add(btnApply))
                .addContainerGap(30, Short.MAX_VALUE))
        );*/

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblSiteName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblSiteCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtSiteCode, 0, 285, Short.MAX_VALUE)
                    .add(txtSiteName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
            //.add(panelButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSiteCode)
                    .add(txtSiteCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSiteName)
                    .add(txtSiteName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                )//.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                //.add(panelButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    /*
    public static void zzzmain(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SiteDialog dialog = new SiteDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField txtSiteCode;
    private javax.swing.JLabel lblSiteCode;
    private javax.swing.JLabel lblSiteName;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JSeparator seperatorButtons;
    private javax.swing.JTextField txtSiteName;
    // End of variables declaration//GEN-END:variables
    
}
