INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('anthropology', 5, 1);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('climatology', 5, 2);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('dating', 5, 3);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('ecology', 5, 4);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('entomology', 5, 5);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('forest dynamics', 5, 6);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('forest management studies', 5, 7);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('forestry', 5, 8);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('geomorphology', 5, 9);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('glaciology', 5, 10);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('hydrology', 5, 11);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('palaeo-ecology', 5, 12);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('provenancing', 5, 13);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('pyrochronology', 5, 14);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('wood biology', 5, 15);
INSERT into tlkpprojecttype (projecttype, vocabularyid, projecttypeid) values ('wood technology', 5, 16);
