#!/bin/bash
echo "*******************" >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log
echo "Postrm run {{SERVER_VERSION}} with $1 argument" >> /var/log/tellervo-installation.log
date '+%R.%S' >> /var/log/tellervo-installation.log
echo "*******************" >> /var/log/tellervo-installation.log

if [ "$1" = 'remove' ]; then
  rm -f /usr/share/tellervo-server/*.backup
  rm -f /usr/share/tellervo-server/server_credentials
  rm -f /usr/share/tellervo-server/set_database_permission.sql
  rm -f /var/www/tellervo/config.php
  rm -f /var/www/tellervo/systemconfig.php

  if [ -d "/var/www/tellervo" ]; then
    rmdir --ignore-fail-on-non-empty /var/www/tellervo
  fi

  if [ -d "/usr/share/tellervo-server" ]; then
    rmdir --ignore-fail-on-non-empty /usr/share/tellervo-server
  fi
elif [ "$1" = 'failed-upgrade' ]; then
  echo "Previous version postrm script failed, but continuing anyway..." >> /var/log/tellervo-installation.log
elif [ "$1" = 'purge' ]; then
  rm -f /usr/share/tellervo-server/*.backup
  rm -f /usr/share/tellervo-server/server_credentials
  rm -f /usr/share/tellervo-server/set_database_permission.sql
  rm -f /var/www/tellervo/config.php
  rm -f /var/www/tellervo/systemconfig.php

  if [ -d "/var/www/tellervo" ]; then
    rmdir --ignore-fail-on-non-empty /var/www/tellervo
  fi

  if [ -d "/usr/share/tellervo-server" ]; then
    rmdir --ignore-fail-on-non-empty /usr/share/tellervo-server
  fi

  echo "Deleting database..."
  su - postgres -c "dropdb tellervo"
  echo "Deleting logs..."
  rm -f /var/log/tellervo-server.log
  exit 0
fi

echo "*******************" >> /var/log/tellervo-installation.log
echo "*******************\n\n\n" >> /var/log/tellervo-installation.log

exit 0
