/*******************************************************************************
 * Copyright (C) 2011 Peter Brewer.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     Peter Brewer
 *     Dan Girshovich
 ******************************************************************************/
package edu.cornell.dendro.corina.admin.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.table.TableRowSorter;

import edu.cornell.dendro.corina.ui.I18n;
import edu.cornell.dendro.corina.admin.SetPasswordUI;
import edu.cornell.dendro.corina.admin.control.CreateNewUserEvent;
import edu.cornell.dendro.corina.admin.control.UpdateUserEvent;
import edu.cornell.dendro.corina.admin.model.SecurityGroupTableModelB;
import edu.cornell.dendro.corina.admin.model.UserGroupAdminModel;
import edu.cornell.dendro.corina.schema.WSISecurityGroup;
import edu.cornell.dendro.corina.schema.WSISecurityUser;
import net.miginfocom.swing.MigLayout;
import javax.swing.JPanel;
import javax.swing.JCheckBox;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/*
 * UserUI.java
 *
 * Created on January 8, 2010, 11:03 AM
 */

/**
 * GUI Class for viewing/editing a users details.
 * 
 * @author  peterbrewer
 */
public class UserUIView extends javax.swing.JDialog implements ActionListener, MouseListener{
    
	private static final long serialVersionUID = 1L;
	WSISecurityUser user = new WSISecurityUser();
	Boolean isNewUser;
	private UserGroupAdminModel mainModel = UserGroupAdminModel.getInstance();
	private SecurityGroupTableModelB groupsModel;
	private TableRowSorter<SecurityGroupTableModelB> groupsSorter;
	
    /** Creates new form UserUI 
     * @wbp.parser.constructor*/
    public UserUIView(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    	isNewUser = true;
        setupGUI();
        internationlizeComponents();
    }
    
    public UserUIView(JDialog parent, boolean modal, WSISecurityUser user) {
        super(parent, modal);
        this.user = user;
        initComponents();
    	isNewUser = false;
    	setupGUI();
    	internationlizeComponents();
    }
    
    private void internationlizeComponents() {
        lblId.setText(I18n.getText("admin.id")+":");
        lblUser.setText(I18n.getText("login.username")+":");
        lblName.setText(I18n.getText("admin.realName")+":");
        chkEnabled.setText(I18n.getText("general.enabled"));
        btnDoIt.setText(I18n.getText("general.ok"));
        btnClose.setText(I18n.getText("general.close"));
        btnSetPwd.setText(I18n.getText("admin.setPassword"));
        lblPassword.setText(I18n.getText("login.password")+":");
        lblPassword2.setText(I18n.getText("admin.confirmPassword")+":");
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("serial")
	private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        chkEnabled = new javax.swing.JCheckBox();
        scrollPane = new javax.swing.JScrollPane();
        tblGroups = new javax.swing.JTable();
        btnDoIt = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnSetPwd = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblId.setText("ID:");

        txtId.setEditable(false);

        lblUser.setText("User name:");

        lblName.setText("Real name:");

        chkEnabled.setText("Account enabled");

        tblGroups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Group", "Description", "Member"
            }
        ) {
            @SuppressWarnings("unchecked")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            @SuppressWarnings("unchecked")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(tblGroups);

        btnDoIt.setText("Apply");

        btnClose.setText("OK");

        btnSetPwd.setText("Reset Password");
        getContentPane().setLayout(new MigLayout("", "[81px][140px,grow][107px][73px]", "[19px][23px][19px][19px][][71px,grow][][][25px]"));
        
        panel_1 = new JPanel();
        getContentPane().add(panel_1, "cell 1 2 3 1,grow");
        panel_1.setLayout(new MigLayout("", "[79.00px,grow][107px,grow]", "[19px]"));
        txtFirstname = new javax.swing.JTextField();
        panel_1.add(txtFirstname, "cell 0 0,growx,aligny top");
        txtLastname = new javax.swing.JTextField();
        panel_1.add(txtLastname, "cell 1 0,growx,aligny top");
        
        panel_2 = new JPanel();
        getContentPane().add(panel_2, "cell 1 3 3 1,grow");
        panel_2.setLayout(new MigLayout("", "[140px,grow][107px][73px]", "[19px]"));
        txtUsername = new javax.swing.JTextField();
        panel_2.add(txtUsername, "cell 0 0 3 1,growx,aligny top");
        
        lblDefaultPermissions = new JLabel();
        lblDefaultPermissions.setText("Default permissions:");
        getContentPane().add(lblDefaultPermissions, "cell 0 4,aligny center");
        
        panel = new JPanel();
        panel.setBorder(null);
        getContentPane().add(panel, "cell 1 4 3 1,grow");
        panel.setLayout(new MigLayout("", "[][][][]", "[]"));
        
        cbxCreate = new JCheckBox("Create");
        panel.add(cbxCreate, "flowx,cell 0 0");
        
        cbxRead = new JCheckBox("Read");
        panel.add(cbxRead, "cell 1 0");
        
        cbxUpdate = new JCheckBox("Update");
        panel.add(cbxUpdate, "cell 2 0");
        
        chkDelete = new JCheckBox("Delete");
        panel.add(chkDelete, "cell 3 0");
        getContentPane().add(scrollPane, "cell 0 5 4 1,grow");
        lblPassword = new javax.swing.JLabel();
        
                lblPassword.setText("Password:");
                getContentPane().add(lblPassword, "cell 0 6,alignx right,aligny center");
        
        panel_3 = new JPanel();
        getContentPane().add(panel_3, "cell 1 6 3 1,grow");
        panel_3.setLayout(new MigLayout("", "[140px,grow][107px][73px]", "[19px]"));
        txtPassword = new javax.swing.JPasswordField();
        panel_3.add(txtPassword, "cell 0 0 3 1,growx,aligny top");
        lblPassword2 = new javax.swing.JLabel();
        
                lblPassword2.setText("Confirm:");
                getContentPane().add(lblPassword2, "cell 0 7,alignx right,aligny center");
        
        panel_4 = new JPanel();
        getContentPane().add(panel_4, "cell 1 7 3 1,grow");
        panel_4.setLayout(new MigLayout("", "[140px,grow][107px][73px]", "[19px]"));
        txtPassword2 = new javax.swing.JPasswordField();
        panel_4.add(txtPassword2, "cell 0 0 3 1,growx,aligny top");
        getContentPane().add(btnSetPwd, "cell 0 8,alignx left,aligny top");
        getContentPane().add(btnDoIt, "cell 2 8,alignx right,aligny top");
        getContentPane().add(btnClose, "cell 3 8,alignx left,aligny top");
        getContentPane().add(lblUser, "cell 0 3,alignx right,aligny center");
        getContentPane().add(lblName, "cell 0 2,alignx right,aligny center");
        getContentPane().add(lblId, "cell 0 0,alignx right,aligny center");
        getContentPane().add(txtId, "cell 1 0 3 1,growx,aligny top");
        getContentPane().add(chkEnabled, "cell 1 1 3 1,alignx right,aligny top");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnClose;
    protected javax.swing.JButton btnDoIt;
    protected javax.swing.JButton btnSetPwd;
    protected javax.swing.JCheckBox chkEnabled;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel lblId;
    protected javax.swing.JLabel lblName;
    protected javax.swing.JLabel lblPassword;
    protected javax.swing.JLabel lblPassword2;
    protected javax.swing.JLabel lblUser;
    protected javax.swing.JScrollPane scrollPane;
    protected javax.swing.JTable tblGroups;
    protected javax.swing.JTextField txtFirstname;
    protected javax.swing.JTextField txtId;
    protected javax.swing.JTextField txtLastname;
    protected javax.swing.JPasswordField txtPassword;
    protected javax.swing.JPasswordField txtPassword2;
    protected javax.swing.JTextField txtUsername;
    private JPanel panel;
    private JCheckBox cbxRead;
    private JCheckBox cbxUpdate;
    private JCheckBox cbxCreate;
    private JCheckBox chkDelete;
    private JLabel lblDefaultPermissions;
    private JPanel panel_1;
    private JPanel panel_2;
    private JPanel panel_3;
    private JPanel panel_4;
    // End of variables declaration//GEN-END:variables
 
	private void setupGUI()
    {
    	this.setLocationRelativeTo(getRootPane());
    	this.lblId.setVisible(false);
    	this.txtId.setVisible(false);
    	    	
    	this.tblGroups.addMouseListener(this);

    	if(isNewUser)
    	{
        	this.setTitle("Create user");
        	btnDoIt.setText("Create");
        	btnClose.setText("Close");
        	btnSetPwd.setVisible(false);   	
        	chkEnabled.setSelected(true);
    	}
    	else
    	{
        	this.setTitle("Edit user");
        	btnDoIt.setText("Apply");
        	btnClose.setText("Close");
        	lblPassword.setVisible(false);
        	txtPassword.setVisible(false);
        	lblPassword2.setVisible(false);
        	txtPassword2.setVisible(false);
	    	if(user.isSetFirstName()) txtFirstname.setText(user.getFirstName());
	    	if(user.isSetLastName())  txtLastname.setText(user.getLastName());
	    	if(user.isSetId()) 		  txtId.setText(user.getId());
	    	if(user.isSetUsername())  txtUsername.setText(user.getUsername());
	    	if(user.isSetIsActive())  chkEnabled.setSelected(user.isIsActive());
    	}
    	
        // Populate groups list
        groupsModel = new SecurityGroupTableModelB(user);
        tblGroups.setModel(groupsModel);
        groupsSorter = new TableRowSorter<SecurityGroupTableModelB>(groupsModel);
        tblGroups.setRowSorter(groupsSorter);
        tblGroups.setEditingColumn(4);
    	
    	this.btnDoIt.addActionListener(this);
    	this.btnClose.addActionListener(this);
    	this.btnSetPwd.addActionListener(this);
    	
    }

	@Override
	public void actionPerformed(ActionEvent e) {
		if(e.getSource()==this.btnClose) 
		{
			this.dispose();
		}	
		else if (e.getSource()==this.btnDoIt)
		{
			saveChangesToUser();
		}
		else if (e.getSource()==this.btnSetPwd)
		{
			SetPasswordUI setPwdDialog = new SetPasswordUI(null, this.user);
			setPwdDialog.setVisible(true);
			setPwdDialog.setModal(true);
			setPwdDialog.setLocationRelativeTo(null);
		}
	}
	
	private void saveChangesToUser()
	{
		user.setFirstName(txtFirstname.getText());
		user.setLastName(txtLastname.getText());
		user.setUsername(txtUsername.getText());
		user.setIsActive(this.chkEnabled.isSelected());
		
		ArrayList<WSISecurityGroup> newMemList = this.groupsModel.getNewGroupMembership();
		for(WSISecurityGroup g:newMemList){
			if(!user.getMemberOves().contains(g.getId())){
				user.getMemberOves().add(g.getId());
			}
		}
		
		if(isNewUser)
		{
		
			// Creating new user
	    	
			// Check passwords match
			String p1 = new String(this.txtPassword.getPassword());
			String p2 = new String(this.txtPassword2.getPassword());
			if(!p1.equals(p2))
			{
				JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
				return;
			}
			p1 = null;
			p2 = null;
			
			//TODO: check to be sure handling passwords like this is ok.
			new CreateNewUserEvent(user, new String(this.txtPassword.getPassword()), this).dispatch();
		}
		else 
		{
			//get original group membership list
			ArrayList<WSISecurityGroup> oldMemList = this.groupsModel.getOrigGroupMembership();
			// Editing existing user
			new UpdateUserEvent(user, oldMemList, newMemList, this).dispatch();
		}
	}

	@Override
	public void mouseClicked(MouseEvent e) {
		if(e.getClickCount()>1)
		{
			// Double clicked on groups table - change users membership accordingly
			Boolean isMember = (Boolean) this.groupsModel.getValueAt(this.tblGroups.getSelectedRow(), 4);
			
			if(isMember)
			{
				groupsModel.setMembershipAt(this.tblGroups.getSelectedRow(), false);
			}
			else
			{
				groupsModel.setMembershipAt(this.tblGroups.getSelectedRow(), true);

			}
			this.tblGroups.repaint();
		}
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
    
}
